# Generated by Django 3.2.7 on 2021-09-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20210916_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='passenger',
            new_name='passengers',
        ),
    ]
